"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {Avatar,Button,Spinner} from "@heroui/react";
import {api,clearToken,getToken} from "@/lib/api";
import type {User} from "@/lib/types";
const links=[{href:"/home",label:"Explore",icon:"⌖"},{href:"/rides",label:"My rides",icon:"↗"},{href:"/wallet",label:"Wallet",icon:"◉"},{href:"/report",label:"Report",icon:"＋"}];
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname();const router=useRouter();const[user,setUser]=useState<User|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{let alive=true;if(!getToken()){router.replace("/login");return;}api<User>("/auth/me").then(value=>{if(alive)setUser(value)}).catch(()=>{clearToken();router.replace("/login")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[router]);async function logout(){try{await api<void>("/auth/logout",{method:"POST"})}catch{}clearToken();router.replace("/login")}if(loading||!user)return <main className="grid min-h-screen place-items-center"><Spinner label="Loading your ride space…" color="success"/></main>;return <div className="app-shell"><header className="sticky top-0 z-30 border-b border-[#e6ebe5] bg-[#f6f8f5]/90 backdrop-blur"><div className="content-wrap flex h-[76px] items-center justify-between"><Link href="/home" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[14px] bg-ink text-xl text-lime">↗</span><span className="text-lg font-black tracking-tight">unicycle<span className="text-leaf">.</span></span></Link><nav className="desktop-nav flex items-center gap-8">{links.map(item=><Link key={item.href} href={item.href} className={path===item.href?"text-sm font-bold text-leaf":"text-sm font-semibold text-muted hover:text-ink"}>{item.label}</Link>)}</nav><div className="flex items-center gap-3"><span className="hidden text-right sm:block"><span className="block text-xs text-muted">Good to see you</span><span className="block max-w-36 truncate text-sm font-bold">{user.name}</span></span><Avatar name={user.name} size="sm" className="bg-[#d8f17c] text-ink"/><Button isIconOnly variant="light" aria-label="Log out" onPress={logout} className="text-muted">↪</Button></div></div></header><main className="content-wrap pb-28 pt-8 md:pb-12">{children}</main><nav className="mobile-nav fixed inset-x-0 bottom-0 z-40 justify-around border-t border-[#e6ebe5] bg-white/95 px-2 pb-[max(env(safe-area-inset-bottom),8px)] pt-2 backdrop-blur">{links.map(item=><Link key={item.href} href={item.href} className={`${path===item.href?"text-leaf":"text-muted"} flex min-w-[62px] flex-col items-center gap-1 text-[11px] font-semibold`}><span className="text-xl leading-5">{item.icon}</span>{item.label}</Link>)}</nav></div>}
